[versions]
slf4j-version = "2.0.0-alpha1"
logback-version = "1.3.0-alpha4"
picocli-version = "4.6.1"
config-version = "15.0.2"
jetbrains-annotations-version = "20.1.0"
jaffree-version = "0.9.8"
math3-version = "3.6.1"
lang3-version = "3.12.0"
jackson-version = "2.12.2"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
config = { group = "fr.raksrinana", name = "utils.config", version.ref = "config-version" }
jaffree = { group = "com.github.kokorin.jaffree", name = "jaffree", version.ref = "jaffree-version" }
commonsMath = { group = "org.apache.commons", name = "commons-math3", version.ref = "math3-version" }
commonsLang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang3-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
