[versions]
log4j2-version = "3.0.0-SNAPSHOT"
log4j2-slf4j-version = "2.14.1"
picocli-version = "4.6.1"
config-version = "15.0.3"
jetbrains-annotations-version = "21.0.1"
jaffree-version = "2021.05.31"
math3-version = "3.6.1"
lang3-version = "3.12.0"
jackson-version = "2.12.3"
progressbar-version = "0.9.2"

[libraries]
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j18-impl", version.ref = "log4j2-slf4j-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
config = { group = "fr.raksrinana", name = "utils.config", version.ref = "config-version" }
jaffree = { group = "com.github.kokorin.jaffree", name = "jaffree", version.ref = "jaffree-version" }
commonsMath = { group = "org.apache.commons", name = "commons-math3", version.ref = "math3-version" }
commonsLang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang3-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
progressbar = { group = "me.tongfei", name = "progressbar", version.ref = "progressbar-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]
